### ISSUE TITLE
Issue: players fall off boat

### ISSUE THREAD

**Issue by shueja** [mosemister/Ships-5-Bukkit-Version#18] opened 2019-08-18 01:36 UTC
Players are left behind airships when they are going at speeds higher than the length of the boat

**Comment by mosemister** [comment] 2019-08-18 05:40
Never had this issue, but I will look into it

**Comment by shueja** [comment] 2019-08-18 15:05
It may be just a lag issue but I cranked the speed up to 10 on a seven block long airship and kept falling off the back

**Comment by mosemister** [comment] 2019-08-18 15:25
Maybe. Ships 6 was designed to stop the falling of the ship by disabling gravity of the Entity before move and then re enabling it after the teleport

**Comment by shueja** [comment] 2019-08-18 19:27
Then it may be an issue where the teleport is not processed before gravity is turned back on

**Comment by mosemister** [comment] 2019-08-18 19:41
No its not that, the code does not continue until the teleportation is done. Ill look into it when I have the chance (been working all day so I haven't yet)

**Comment by mosemister** [comment] 2019-08-26 22:13
Were the players standing on half blocks or stairs?

**Comment by shueja** [comment] 2019-08-27 15:07
Actually I might have been. The ship that was having this problem is only 3 blocks wide and the outside blocks are stairs

**Comment by mosemister** [comment] 2019-08-27 17:54
Ok. If so the issue should be resolved in version alpha 2.4

**Comment by shueja** [comment] 2019-08-28 00:42
It’s not just stairs though. However I did notice that when in fly mode hovering just above the floor in front of the move sign I was teleported just fine so I think it’s an issue with the no gravity

**Comment by mosemister** [comment] 2019-08-28 09:19
As mentioned before, it can not be that as the code grabs the entities before no gravity is activated. Even with lag it wouldnt make them fall off. 

Ill try with a 3 wide ship and see what happens.

**Comment by mosemister** [comment] 2019-09-22 17:37
Has this been fixed on your end?

**Comment by shueja** [comment] 2019-09-22 17:59
Sorry haven’t had time to check. I’ll put it on my list of in game tasks and get back to you.

**Comment by mosemister** [comment] 2020-01-13 23:13
Closed due to a lack of response

**Closed as completed by mosemister** 2020-01-13 23:13 UTC
Labels: bug
