### ISSUE TITLE
Error with /ships shiptype

### ISSUE THREAD

**Issue by normanfeltz** [mosemister/Ships-5-Bukkit-Version#14] opened 2019-08-14 10:32 UTC
Hi,

I have a error with your plugin :
The plugin was in v6.0.0.0
The spigot server: git-Spigot-1a3504a-84f3da3 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

`[12:29:48] [Server thread/INFO]: normanfeltz issued server command: /ships shiptype
[12:29:48] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'ships' in plugin Ships v6.0.0.0
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:48) ~[Spigot-1.13.jar:git-Spigot-1a3504a-84f3da3]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[Spigot-1.13.jar:git-Spigot-1a3504a-84f3da3]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:704) ~[Spigot-1.13.jar:git-Spigot-1a3504a-84f3da3]
	at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1621) ~[Spigot-1.13.jar:git-Spigot-1a3504a-84f3da3]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1461) ~[Spigot-1.13.jar:git-Spigot-1a3504a-84f3da3]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[Spigot-1.13.jar:git-Spigot-1a3504a-84f3da3]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[Spigot-1.13.jar:git-Spigot-1a3504a-84f3da3]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:9) ~[Spigot-1.13.jar:git-Spigot-1a3504a-84f3da3]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_212]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_212]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [Spigot-1.13.jar:git-Spigot-1a3504a-84f3da3]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896) [Spigot-1.13.jar:git-Spigot-1a3504a-84f3da3]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [Spigot-1.13.jar:git-Spigot-1a3504a-84f3da3]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [Spigot-1.13.jar:git-Spigot-1a3504a-84f3da3]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [Spigot-1.13.jar:git-Spigot-1a3504a-84f3da3]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at org.ships.commands.legacy.shiptype.LegacyShipTypeCommand.run(LegacyShipTypeCommand.java:28) ~[?:?]
	at org.ships.commands.legacy.LegacyShipsCommand.run(LegacyShipsCommand.java:62) ~[?:?]
	at org.ships.implementation.bukkit.command.BCommand.onCommand(BCommand.java:24) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[Spigot-1.13.jar:git-Spigot-1a3504a-84f3da3]
	... 15 more`

Cordialy

Norman F.

**Comment by mosemister** [comment] 2019-08-14 16:48
The issue comes from this line https://github.com/Minecraft-Ships/ShipsForCore/blob/30f9f484791940b7df4f0b01944369663139d454/src/org/ships/commands/legacy/shiptype/LegacyShipTypeCommand.java#L28

As a server admin, you should not be worried, but I will fix the issue in the next update. The issue is caused when a user attempts to use the /ships shiptype command without any arguments

**Comment by mosemister** [comment] 2019-08-22 17:15
Fixed in alpha 2.2

**Closed as completed by mosemister** 2019-08-22 17:15 UTC
Labels: bug
