### ISSUE TITLE
Feature request/ Issue: Waterlogged blocks on airship leave water abnormalities. 

### ISSUE THREAD

**Issue by shueja** [mosemister/Ships-5-Bukkit-Version#25] opened 2019-08-29 15:56 UTC
The issue here is likely down to water source block creation because of two waterlogged blocks adjacent to the same block. 
Suggested resolution: unwaterlog all blocks on move/altitude change

**Comment by mosemister** [comment] 2019-08-29 16:17
So just making sure, is it two waterlogged blocks next to eachother or is it two waterlogged blocks next to a block?

**Comment by shueja** [comment] 2019-08-29 16:25
I can’t actually tell which waterlogged blocks are making the source block because it happens when I build part of a ship underwater and then try to take off and the blocks are waterlogged. It’s not causing problems until the blocks get updated, and then the hull of the ship is pouring water. Is there any way to have the blocks below water waterlogged and the the blocks above water get unwaterlogged?

**Comment by mosemister** [comment] 2019-08-29 16:27
Waterlogged blocks have not yet been tested. So to answer you question, no. 

Ill take a look at them when I get the chance.

**Comment by shueja** [comment] 2019-08-29 16:49
Ok cool

**Comment by mosemister** [comment] 2019-09-02 19:08
I found the issue. The issue is that it doesn't create source blocks, it actually removes the source block (as in the water logged block), the issue is that the block removal doesnt update its nabour blocks to save on performance. Because water flowing requires a water source and the flowing block still thinks the block above it is the source block (when its not), it keeps itself there. 

I have updated my internal build of ships to fix the issue so you will have it next release.

**Comment by mosemister** [comment] 2019-09-07 18:12
Is this issue fixed now?

**Comment by shueja** [comment] 2019-09-08 03:24
Don’t know, I haven’t had the chance to update recently

**Comment by mosemister** [comment] 2020-01-13 23:11
Closed issue due to a lack of response

**Closed as completed by mosemister** 2020-01-13 23:11 UTC
Labels: bug
